name: Build OBS with ffmpeg-rockchip

on:
  workflow_dispatch:
    inputs:
      obs_version:
        description: "OBS Studio tag/version (e.g. 32.0.0)"
        required: false
        default: "32.0.0"
        type: string
      ffmpeg_branch:
        description: "ffmpeg-rockchip branch/tag (e.g. 6.1)"
        required: false
        default: "6.1"
        type: string
      cef_version:
        description: "CEF version (e.g. 127.3.5+g114ea2a+chromium-127.0.6533.120)"
        required: false
        default: "127.3.5+g114ea2a+chromium-127.0.6533.120"
        type: string
      ignore_cache:
        description: "Ignore/disable dependency cache for a clean build"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: write
    env:
      OBS_VERSION: ${{ inputs.obs_version }}
      FFMPEG_BRANCH: ${{ inputs.ffmpeg_branch }}
      CEF_VERSION: ${{ inputs.cef_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache all dependencies
        uses: actions/cache@v4
        if: ${{ !inputs.ignore_cache }}
        with:
          path: |
            ${{ github.workspace }}/.ccache
            ${{ github.workspace }}/install/ffmpeg-rockchip
            ${{ github.workspace }}/cef
            ${{ github.workspace }}/cef.tar.bz2
            /tmp/libdatachannel*.deb
          key: all-cache-${{ runner.os }}-${{ inputs.cef_version }}-${{ hashFiles('scripts/build-obs-rockchip.sh') }}
          restore-keys: |
            all-cache-${{ runner.os }}-${{ inputs.cef_version }}-
            all-cache-${{ runner.os }}-

      - name: Make script executable
        run: chmod +x scripts/build-obs-rockchip.sh

      - name: Build OBS with ffmpeg-rockchip
        env:
          WORKSPACE: ${{ github.workspace }}
          NUM_JOBS: 4
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          USE_CCACHE: ${{ inputs.ignore_cache && '0' || '1' }}
        run: scripts/build-obs-rockchip.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obs-rockchip-debs-${{ env.OBS_VERSION }}
          path: artifacts/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.OBS_VERSION }}-rockchip-browser"
          name: "OBS Studio ${{ env.OBS_VERSION }} for Rockchip (with Browser)"
          body: |
            ## OBS Studio ${{ env.OBS_VERSION }} for Rockchip ARM64 with Browser Support
            
            A specialized build of OBS Studio optimized for Rockchip ARM64 platforms (RK3588/RK3588s) with:
            
            ### Features
            - **Hardware-accelerated encoding/decoding** using Rockchip MPP (Media Process Platform)
            - **2D graphics acceleration** using Rockchip RGA (Raster Graphic Acceleration) 
            - **Browser source support** using CEF ${{ env.CEF_VERSION }}
            - **Custom FFmpeg** with Rockchip extensions (branch: ${{ env.FFMPEG_BRANCH }})
            - **Qt6 interface** with Wayland support
            - **PipeWire audio** support
            
            ### Installation
            ```bash
            sudo dpkg -i obs-studio_*.deb
            sudo apt-get install -f  # Fix any dependency issues
            ```
            
            ### Compatibility
            - Tested on Ubuntu 24.04 ARM64
            - Requires Rockchip RK3588/RK3588s SoC
            - Requires Mesa drivers with DRM support
            
            Built on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          files: artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}