name: Build OBS with ffmpeg-rockchip

on:
  workflow_dispatch:
    inputs:
      obs_version:
        description: "OBS Studio tag/version (e.g. 32.0.0)"
        required: false
        default: "32.0.0"
        type: string
      ffmpeg_branch:
        description: "ffmpeg-rockchip branch/tag (e.g. 6.1)"
        required: false
        default: "6.1"
        type: string
      ignore_cache:
        description: "Ignore/disable dependency cache for a clean build"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: write
    env:
      OBS_VERSION: ${{ inputs.obs_version }}
      FFMPEG_BRANCH: ${{ inputs.ffmpeg_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache all dependencies
        uses: actions/cache@v4
        if: ${{ !inputs.ignore_cache }}
        with:
          path: |
            ${{ github.workspace }}/.ccache
            ${{ github.workspace }}/install/ffmpeg-rockchip
            /tmp/cef.tar.bz2
            /tmp/libdatachannel*.deb
          key: all-cache-${{ runner.os }}-${{ hashFiles('scripts/build-obs-rockchip.sh') }}
          restore-keys: |
            all-cache-${{ runner.os }}-

      - name: Make script executable
        run: chmod +x scripts/build-obs-rockchip.sh

      - name: Build OBS with ffmpeg-rockchip
        env:
          WORKSPACE: ${{ github.workspace }}
          NUM_JOBS: 4
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          USE_CCACHE: ${{ inputs.ignore_cache && '0' || '1' }}
        run: scripts/build-obs-rockchip.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obs-rockchip-debs
          path: artifacts/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.OBS_VERSION }}-rockchip"
          name: "${{ env.OBS_VERSION }}-rockchip"
          body: |
            ## ${{ env.OBS_VERSION }}-rockchip
            
            A specialized build of OBS Studio optimized for Rockchip ARM64 platforms (RK3588/RK3588s) with hardware-accelerated video encoding and decoding using Rockchip's MPP (Media Process Platform) and RGA (2D Raster Graphic Acceleration) libraries.
          files: artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


